### ISSUE TITLE
[meta] make children registration page fully functional

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/mondey#23]
- refactor the component to get rid of excessive indirection and abstraction.
- link children registration page to the correct place
- add functionality: 
  - [x] new child data needs to be added to child data of user #28 
  - [x] new child data needs to be verified #28 
  - [x] new child needs to have a new open survey that is completely `not started yet` with the respective data it was added  (this will be added to the children store)
