### ISSUE TITLE
[meta] make user login functional and add interaction with the rest of the page

### ISSUE THREAD

**Issue by MaHaWo** [ssciwr/mondey#25]
- needs to be worked on once the user store and the registration page are there 
- user login needs to work: 
 - [x] accept known password and user token #34 
 - [x] verification and rerouting when wrong credentials are given #34 
 - [x] new `forgot password`  page
 - [x] new `home page` for a user that shows menu with profile settings etc and children overview
 - [x] data needs to be fetched from store/dummy backend.

It is probably sensible to split this up into multiple PRs.

**Comment by MaHaWo** [comment]
closed as completed
